-- Check PagePermission table structure
SELECT 
    c.COLUMN_NAME as [Column],
    c.DATA_TYPE as [Type],
    c.IS_NULLABLE as [Nullable],
    CASE WHEN pk.COLUMN_NAME IS NOT NULL THEN 'PK' ELSE '' END as [Key]
FROM INFORMATION_SCHEMA.COLUMNS c
LEFT JOIN (
    SELECT ku.COLUMN_NAME
    FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
    JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE ku ON tc.CONSTRAINT_NAME = ku.CONSTRAINT_NAME
    WHERE tc.TABLE_NAME = 'PagePermission' AND tc.CONSTRAINT_TYPE = 'PRIMARY KEY'
) pk ON c.COLUMN_NAME = pk.COLUMN_NAME
WHERE c.TABLE_NAME = 'PagePermission'
ORDER BY c.ORDINAL_POSITION;

-- Check unique constraints
SELECT 
    tc.CONSTRAINT_NAME as [Constraint],
    STRING_AGG(ku.COLUMN_NAME, ', ') WITHIN GROUP (ORDER BY ku.ORDINAL_POSITION) as [Columns]
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE ku ON tc.CONSTRAINT_NAME = ku.CONSTRAINT_NAME
WHERE tc.TABLE_NAME = 'PagePermission' AND tc.CONSTRAINT_TYPE = 'UNIQUE'
GROUP BY tc.CONSTRAINT_NAME;
