export const mappingGuide = {
  balanceSheet: {
    nonCurrentLiabilities: [
      { sarsItem: "Long-term loans - interest free: Connected (Local)" },
      { sarsItem: "Long-term loans - interest free: Non-Connected (Local)" },
      { sarsItem: "Long-term loans - interest free: Connected (Foreign)" },
      { sarsItem: "Long-term loans - interest free: Non-Connected (Foreign)" },
      { sarsItem: "Long-term loans - interest bearing: Connected (Local)" },
      { sarsItem: "Long-term loans - interest bearing: Non-Connected (Local)" },
      { sarsItem: "Long-term loans - interest bearing: Connected (Foreign)" },
      { sarsItem: "Long-term loans - interest bearing: Non-Connected (Foreign)" },
      { sarsItem: "Deferred tax liability" },
      { sarsItem: "Other non-current liabilities"}
    ],
    currentLiabilities: [
      { sarsItem: "Gross trade and other payables (Not older than 3 years)" },
      { sarsItem: "Gross trade and other payables (Older than 3 years)" },
      { sarsItem: "Provisions - excluding inventory and trade receivables" },
      { sarsItem: "Deposits and funds received in advance (excl. contract progress payments)" },
      { sarsItem: "Group companies current accounts" },
      { sarsItem: "Contract progress payments received in advance" },
      { sarsItem: "Current portion of interest bearing borrowings" },
      { sarsItem: "Current portion of interest free borrowings" },
      { sarsItem: "Overdraft and interest bearing short-term borrowings" },
      { sarsItem: "SA Revenue Service" },
      { sarsItem: "Shareholders for dividend / proposed dividend" },
      { sarsItem: "Other current liabilities"}
    ],
    nonCurrentAssets: [
      { sarsItem: "Long-term loans - interest free: Connected (Local)" },
      { sarsItem: "Long-term loans - interest free: Non-Connected (Local)" },
      { sarsItem: "Long-term loans - interest free: Connected (Foreign)" },
      { sarsItem: "Long-term loans - interest free: Non-Connected (Foreign)" },
      { sarsItem: "Long-term loans - interest bearing: Connected (Local)" },
      { sarsItem: "Long-term loans - interest bearing: Non-Connected (Local)" },
      { sarsItem: "Long-term loans - interest bearing: Connected (Foreign)" },
      { sarsItem: "Long-term loans - interest bearing: Non-Connected (Foreign)" },
      { sarsItem: "Deferred tax assets" },
      { sarsItem: "Other non-current assets"}
    ],
    currentAssets: [
      { sarsItem: "Gross inventory (incl. spare parts and consumables and work in progress)" },
      { sarsItem: "Less: Provisions for inventory write off" },
      { sarsItem: "Gross trade and other receivables (excl. debtors)" },
      { sarsItem: "Less: Provisions for trade and other receivables (excl debtors)" },
      { sarsItem: "Gross debtors (excl. trade debtors)" },
      { sarsItem: "Less: Provisions for debtors (excl. trade debtors)" },
      { sarsItem: "Prepayments" },
      { sarsItem: "Group companies current accounts" },
      { sarsItem: "Short-term investments" },
      { sarsItem: "SA Revenue Service" },
      { sarsItem: "Cash and cash equivalents" },
      { sarsItem: "Other current assets"}
    ],
    capitalAndReservesCreditBalances: [
      { sarsItem: "Share capital" },
      { sarsItem: "Share premium" },
      { sarsItem: "Non-distributable reserves for credit balances" },
      { sarsItem: "Distributable reserves (excl. retained profit / accumulated loss)" },
      { sarsItem: "Retained profit" },
      { sarsItem: "Other capital and reserves"}
    ],
    capitalAndReservesDebitBalances: [
      { sarsItem: "Accumulated loss" },
      { sarsItem: "Other capital and reserves for debit balances"}
    ]
  },
  incomeStatement: {
    grossProfitOrLoss: [
      { sarsItem: "Gross Sales (excl. credit notes) - Foreign: Connected" },
      { sarsItem: "Gross Sales (excl. credit notes) – Other than foreign connected" },
      { sarsItem: "Less: Opening stock" },
      { sarsItem: "Less: Credit notes on sales" },
      { sarsItem: "Less: Purchases - Foreign: Connected (excl. rebates)" },
      { sarsItem: "Less: Purchases - Other than foreign connected (excl. rebates)" },
      { sarsItem: "Add: Rebates" },
      { sarsItem: "Add: Closing stock (Gross excl. adjustments)" },
      { sarsItem: "Add: Inventory adjustments (Previous year stock provision reversed)" },
      { sarsItem: "Less: Inventory adj. (Current year stock provision (obsolete / slow-moving stock))" }
    ],
    incomeItemsCreditAmounts: [
      { sarsItem: "Accounting profit on disposal of fixed assets and / or other assets" },
      { sarsItem: "Admin., management, secretarial, rentals, guarantee fees and other services – Connected (Local)" },
      { sarsItem: "Admin., management, secretarial, rentals, guarantee fees and other services – Connected (Foreign)" },
      { sarsItem: "Admin., management, secretarial, rentals, guarantee fees and other services – Non-connected" },
      { sarsItem: "Amounts deemed to be dividends in specie (s8F and s8FA)" },
      { sarsItem: "Bad and doubtful debts recovered" },
      { sarsItem: "Dividends - local" },
      { sarsItem: "Dividends - foreign" },
      { sarsItem: "Dividends (local and foreign) deemed to be income (s8E and s8EA)" },
      { sarsItem: "Tainted Dividends (local and foreign) deemed to be income (s22B)" },
      { sarsItem: "Fruitless and wasteful expenditure recovered during this year of assessment" },
      { sarsItem: "Foreign exchange gain" },
      { sarsItem: "Government grants (national, provincial and local)" },
      { sarsItem: "Gross royalties and license fees" },
      { sarsItem: "Indemnity payments received" },
      { sarsItem: "Insurance proceeds received" },
      { sarsItem: "Interest - Financial institutions" },
      { sarsItem: "Interest - Connected" },
      { sarsItem: "Interest - Non-Connected (excluding SARS interest (s7E))" },
      { sarsItem: "SARS Interest (s7E))" },
      { sarsItem: "Levy income" },
      { sarsItem: "REIT distributions received" },
      { sarsItem: "Reversal of impairment loss recognised in profit or loss" },
      { sarsItem: "Other income"}
    ],
    expenseItemsDebitAmounts: [
      { sarsItem: "Accommodation and travel expenses: Local" },
      { sarsItem: "Accommodation and travel expenses: Foreign" },
      { sarsItem: "Accounting loss on disposal of fixed assets / other assets" },
      { sarsItem: "Admin., secretarial, rentals, guarantee fees and other services – Connected (Local)" },
      { sarsItem: "Admin., secretarial, rentals, guarantee fees and other services – Connected (Foreign)" },
      { sarsItem: "Admin., secretarial, rentals, guarantee fees and other services – Non-connected" },
      { sarsItem: "Alterations and improvements (excluding repairs and maintenance)" },
      { sarsItem: "Bad debts written off" },
      { sarsItem: "Capital improvements - farming operations (par 12 of the First Schedule)" },
      { sarsItem: "Commission paid" },
      { sarsItem: "Compensation for loss of office" },
      { sarsItem: "Consulting, legal and professional fees" },
      { sarsItem: "Depreciation" },
      { sarsItem: "Directors' / members' remuneration" },
      { sarsItem: "Donations (s18A)" },
      { sarsItem: "Donations - other" },
      { sarsItem: "Employee expenses: Wages and salaries (excluding medical, provident and pension)" },
      { sarsItem: "Employee expenses: Group life insurance" },
      { sarsItem: "Employee expenses: UIF contributions and SDL" },
      { sarsItem: "Employee expenses: Pension and Provident fund contributions" },
      { sarsItem: "Employee expenses: Medical scheme contributions" },
      { sarsItem: "Employee expenses: Membership of a professional body" },
      { sarsItem: "Employee expenses: Training" },
      { sarsItem: "Expenditure incurred by a lessor of land let for farming purposes in respect of soil erosion (s17A)" },
      { sarsItem: "Expenditure incurred directly or indirectly in effecting BEE and / or BBEEE compliance" },
      { sarsItem: "Expenditure incurred in respect of company restructuring" },
      { sarsItem: "Foreign exchange loss" },
      { sarsItem: "Impairment loss recognised in profit or loss" },
      { sarsItem: "Insurance (excluding s37A payments)" },
      { sarsItem: "Insurance premium in respect of rehabilitation obligations (s37A)" },
      { sarsItem: "Interest - financial institutions" },
      { sarsItem: "Interest - Connected (Local)" },
      { sarsItem: "Interest - Connected (Foreign)" },
      { sarsItem: "Interest - Non-connected" },
      { sarsItem: "Interest and penalties paid to SARS (excluding SARS interest repaid that was previously taxed i.t.o. s7E)" },
      { sarsItem: "Key man insurance (s11(w))" },
      { sarsItem: "Lease payments other than operating leases" },
      { sarsItem: "Management fees - Connected" },
      { sarsItem: "Management fees - Non-connected" },
      { sarsItem: "Operating lease payments - Connected" },
      { sarsItem: "Operating lease payments - Non-connected" },
      { sarsItem: "Partnership / Joint venture loss - Foreign" },
      { sarsItem: "Partnership / Joint venture loss - Local" },
      { sarsItem: "Provision for doubtful debts" },
      { sarsItem: "Research and development costs (s11D)" },
      { sarsItem: "Restraint of trade" },
      { sarsItem: "Repair and maintenance" },
      { sarsItem: "Small items and loose tools" },
      { sarsItem: "Other expenses (excluding items listed above)"}
    ],
    incomeItemsOnlyCreditAmounts: [
      { sarsItem: "Royalties and license fees (excluding payments in terms of mineral and petroleum resources royalties) - Local" },
      { sarsItem: "Royalties and license fees (excluding payments in terms of mineral and petroleum resources royalties) – Foreign" },
      { sarsItem: "Mineral and Petroleum Resources royalty" }
    ]
  }
};

